### ISSUE TITLE
Portal Structures

### ISSUE THREAD

**Issue by gmlaxfanatic** [Civcraft/BetterShards#1]
ttk suggested I touch base with you about the portal plugin, and I think I might be able to help you out a good bit there.

I am building in support for arbitrary structures into Contraptions. So any .schematic file (ie. those on http://www.minecraft-schematics.com/) can be loaded up on the plugin and used as a requirement for a functional structure in the minecraft world. Depending on your plans for portals I could see an implementation where a contraption handles all the interactions between the player and minecraft blocks, and also handles maintenance and creation if you are including those mechanics. Then when the player interacts with the portal in a specific way Contraptions throws an event which the portal plugin grabs and does its magic with.

I'd like to hear a lot more of what you are shooting for with portal structure/mechanics and then I can let you know where I think Contraptions could help you out.

**Comment by rourke750** [comment]
Hey so I had a few things in mind.
1. Some layover region where entering the field would initiate teleport.  By default I will add this since it wouldn't need any external dependencies like factorymod.
2. Some kind of structure but I couldn't think of any good ways to to track the shape without using a cuboid.  

But having Contraptions throw an event with certain factory creations, breaks, interactions would be useful.  Would you be able to create a Properties interface.  That way I could inherit that class and give it certain properties.  Then when a certain event is thrown I could grab those properties and interact with it that way.

**Comment by gmlaxfanatic** [comment]
1. Sounds like a good plan

I've got some questions about your plans for the structure
1. Is it something that is generated with the world, or created by players? 
2. Can it be destroyed? Is that something that needs to be actively monitored? 
3. Approximately what cubic dimensions will it be?

I'd be amenable to a properties interface, but would want a better understanding of its use cases before proceeding.

**Comment by rourke750** [comment]
1. With support in contraptions we could do random generation but regions would be created by admins and of course multi block structures could be either set via admins or handled differently if built by users.
2. Admin set up ones no, but with Citadel we can make them invulnerable.
3. Depends on what the end user wants to set up.  You should look into JukeAlert's class here: https://github.com/Civcraft/JukeAlert/blob/master/src/com/untamedears/JukeAlert/util/SparseQuadTree.java 
   it allows a lot of scaling with high performance benefits.

**Comment by gmlaxfanatic** [comment]
If portals aren't user created/destroyed I don't think contraptions will be useful. Its main benefit is it makes creating/destroying arbitrary structures very easy to do. But it sounds like the portals are likely admin created invulnerable creations so this is not needed. I think there are server tools for pasting .schematic files out there for the initial creation.

How many portals are we planning on having, if its <100 per shard you probably don't even have to get as complicated as a sparse quad tree (I've read through namelayer's implementation before). Instead you could just do direct lookups through a Map which would be O(1), since the size of the Map wouldn't be that great.

**Comment by ttk2** [comment]
considering the planned ideal shared size <100 should suffice.
