### ISSUE TITLE
Spawning behavior 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/BetterShards#12]
BetterShards should provide a config option with a list of "spawning worlds" when a player dies without a bed a spawning world will be selected at random from the list and a location within that world also selected at random the player will then be respawned at that location. 

Optional features: 

 when configuring spawning worlds allow for bounding boxes for where people spawn inside those worlds

add a feature to weight the location selected to places nearby players.

**Comment by Maxopoly** [comment]
Mostly done, replaced by https://github.com/Civcraft/BetterShards/issues/30
