### ISSUE TITLE
Cross shard player data

### ISSUE THREAD

**Issue by erocs** [Civcraft/BetterShards#22]
As multi-shard support matures, the need arises for plugins to hold account specific data which needs to migrate with the account between shards. This data is not globally available between shards.

Current design thoughts:
- Leverage a TreeMap<UUID, org.bukkit.configuration.file.YamlConfiguration> to hold separate configurations per account. This would be a private field in BetterShards.
- Provide a org.bukkit.configuration.ConfigurationSection retrieveData(Plugin, UUID) public method in the BetterShards API, allowing plugins to retrieve a plugin specific data repository. Using Bukkit's ConfigurationSection provides familiarity for plugin authors and handles serialization.
- The YamlConfiguration would be setup with a separate ConfigurationSection for each plugin, keyed to the plugin's name. The plugin name may need to be normalized for use as a YAML map key.
- The YamlConfiguration would be serialized and deserialized to Strings (instead of Files) and stored in the DB table in a new column beside the account's NBT data.
- As an account's NBT data is saved and restored on a shard, this data would also be saved and restored.

**Comment by rourke750** [comment]
https://github.com/Civcraft/BetterShards/commit/66377ee1aea2a759dd1715e855421a98d15e69b7#diff-57d1dd804110cb41caf6042af59aeb50
