### ISSUE TITLE
/bsj doesn't cause linked portal to function

### ISSUE THREAD

**Issue by erocs** [Civcraft/BetterShards#28]
Supposedly a restart might fix it. It should just work though.

**Comment by rourke750** [comment]
Nothing is wrong with the command.  A stack from earlier borked the plugin for teleporting.

**Comment by erocs** [comment]
So what's the fix?

**Comment by rourke750** [comment]
https://github.com/Civcraft/BetterShards/commit/bc81e308493f2caaf3ff24575008826a5039ca75
