### ISSUE TITLE
Vanished players show on the tab-list

### ISSUE THREAD

**Issue by erocs** [Civcraft/BetterShards#37]
This might be a problem with BungeeCord itself.

**Comment by erocs** [comment]
We'd need to use something outside of Vanish. Maybe a new bettershards command that Mercury sends vanished status to bungeecord. Then it might take a custom bungeecord.

http://wiki.vg/Protocol#Player_List_Item
https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/packet/PlayerListItem.java
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L112
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/tab/Global.java

**Comment by Maxopoly** [comment]
Not a BetterShards issue, this is a problem between VanishNoPacket and tablist plugins living in the bungee layer
