### ISSUE TITLE
Add custom packets for mods

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/BetterShards#39]
So since shards could potentially (and probably will) have the same coordinates multiple times, I think we need a way to let mod devs know what shard a player is in. This could be done with a command but I think it would be better and less intrusive to use custom packets. There would be two packets the client can send, one to check if bettershards is enabled (just a basic ping and empty response) as well as a packet to check what shard the player is in currently, hopefully identified with a numeric id and name. Thoughts @erocs ?

**Comment by erocs** [comment]
https://github.com/Civcraft/Mercury/blob/master/src/vg/civcraft/mc/mercury/MercuryAPI.java#L92 ?

Although as we continue forward with BetterShards, I wonder why Mercury is doing the player tracking.

**Comment by rourke750** [comment]
@erocs He means client side.
@TealNerd You can't implement custom packets it would crash the client.  Instead you would have to use something like bukkitmessaging channels.

**Comment by TealNerd** [comment]
right rourke that's what I meant, using https://dinnerbone.com/blog/2012/01/13/minecraft-plugin-channels-messaging/

**Comment by erocs** [comment]
Arguably we should add a player /shard command into BetterShards so all players can readily see what shard they are on. Custom clients could just run that to check the current shard.

**Comment by TealNerd** [comment]
Yeah that would work as well

**Comment by TealNerd** [comment]
@erocs @rourke750 also thoughts on putting this online to be compatible with journeymap and voxelmap? http://dev.bukkit.org/bukkit-plugins/worldinfo/

**Comment by ProgrammerDan** [comment]
License looks good, we'd have to test it out but code seems simple and straightforward.

**Comment by erocs** [comment]
I'm conflicted. We only support vanilla.

**Comment by ProgrammerDan** [comment]
That's the beauty of this. It's using a vanilla mechanism to "play nice" with optional client mods. No impact to vanilla clients that are unmodded.
