### ISSUE TITLE
Add /shard command to reveal current shard

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/BetterShards#40]
Gratuitously stealing from Erocs.

Add /shard that shows the current shard name. This is preferable to providing specific advantages to mods ( #39 ) which although would probably be fine opens us up to a path of development we might want to avoid (optimizing for direct mod development, etc. etc).

**Comment by TealNerd** [comment]
So are we not going to use the WorldInfo plugin at all? I get if that's how y'all want it, but I think the community and even personal mapping is a big deal on Civ and won't be possible with any currently existing mods without that

**Comment by erocs** [comment]
I think we just need to decide upon what level of support we will provide for client mods. Using this might leave us with another plugin to maintain, if the dev goes inactive or we require specific changes for civcraft.

**Comment by TealNerd** [comment]
I think it could at least be cool to have while I work on making a mapping mod that supports bettershards using the /shard command. It kinda just generally sucks cus without a new mod or the use of that plugin mapping will just not be possible.

**Comment by ghost** [comment]
Doesn’t voxelmap support shard mapping if the user enables the multiworld feature?

**Comment by TealNerd** [comment]
the multiworld feature doesn't actually work without either WorldInfo or JourneymapServer installed server side. Basically without either of those everything overworld overlaps as does everything nether and end

**Comment by ghost** [comment]
Ahh I see

**Comment by ProgrammerDan** [comment]
The voxelmap multiworld features work without any additional serverside iirc. You just have to manually turn it on per server and manually enter the world name as you visit it. 

I guess voxel >> journeymap.

Since both are secret-source, it's no wonder. Both products would be so much better if they just shared source ...

**Comment by TealNerd** [comment]
Voxelmap MW hasn't really worked for me. I tried it out on Devoted and it let me set worlds but kept overriding map data because it can't determine which world you're in when you switch

**Comment by Maxopoly** [comment]
Yeah, MW without that server mod requires you to manually select a world every time you switch worlds or relog.

**Comment by Maxopoly** [comment]
No longer needed, because of WorldInfo.
