### ISSUE TITLE
Lock a player on beginning of shard transition

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/BetterShards#43]
When a player enters the portal, step 1 should be "locking" them so they can't move, interact with inventories or objects, or be struck or hurt. This is to prevent CT spawning in a combat logger and duplicating inventories if tagged during transition.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/BetterShards/commit/a376834f89e8527f95f8573759474968e0cb885e
