### ISSUE TITLE
Change Fallback mechanic

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/BetterShards#59]
Either we get an actual lobby or we throw out the fall back stuff, because throwing people somewhere in Aleph is kind of a bad idea.

**Comment by ttk2** [comment]
We can setup a lobby pretty easily, hell we had some people build creative mode stuff for it right? The issue is explaining to people how it works. 

It might be simpler for them to understand if we just kicked them with the message "the shard you where on is experiencing issues please wait"

**Comment by rourke750** [comment]
Going to piggie back this.  just need a server to dump players once they log in and then to know where a player needs to be and ping a server and wait for it to come back up.  Once it gets the communication from mercury resend them over.  Maybe even use the enum thing i set up with custom invs to make it so they have a new account so they cant interact and fuck up anything.

**Comment by ttk2** [comment]
and if the wait is long?

**Comment by Maxopoly** [comment]
Then they have to wait in the lobby server for a long time. This is still by far the best solution, the only other one would be to refuse their login completly until the server is back up
