### ISSUE TITLE
License has wrong plugin name

### ISSUE THREAD

**Issue by Ryan00793** [Civcraft/BetterShards#70]
look at the plugin name on the license

**Comment by ttk2** [comment]
thanks for letting us know! our licensing efforts have been subpar.

**Comment by ProgrammerDan** [comment]
Bonus, we also know the plugin rourke forked when he started this one :)

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/BetterShards/commit/50a5ebb517aa703f19b5ed2017c513a5d13cb7e9
