### ISSUE TITLE
RandomSpawn plugin should allow random spawns in other worlds

### ISSUE THREAD

**Issue by rourke750** [Civcraft/BetterShards#71]
modify code to allow spawning in other worlds.

**Comment by Maxopoly** [comment]
If only someone [added a config option](https://github.com/Civcraft/BetterShards/blob/master/BetterShardsBukkit/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java#L82)  for that...

This is part of why I dislike the civconfig stuff, you have to dig through code to actually find the options you need

**Comment by rourke750** [comment]
Meant via plugin api

**Comment by Maxopoly** [comment]
Wait you mean, that someone is in shard X and you want to randomspawn them in shard Y?

**Comment by rourke750** [comment]
No someone is in shard x and wants to random spawn them in shard y to a
different world

**Comment by Maxopoly** [comment]
But we only have one world per shard?

**Comment by Maxopoly** [comment]
It does now
