### ISSUE TITLE
Add command similar to bungee's /server

### ISSUE THREAD

**Issue by erocs** [Civcraft/BetterShards#90]
It should tell a player what shard they are on and what shards are currently online.

**Comment by rourke750** [comment]
So like glist and find command?

**Comment by rbp15** [comment]
Will the player be able to run this command from the Lobby?

**Comment by rourke750** [comment]
Oh lol. I misread what he said.  Alright yea this needs to be coded.

**Comment by rourke750** [comment]
And yes they will.

**Comment by rbp15** [comment]
Cool - thanks!

**Comment by rourke750** [comment]
https://github.com/Civcraft/BetterShards/pull/93
